apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: todo.local           # What hostname?
    http:
      paths:
      - path: /       # What path?
        pathType: Prefix   # Prefix or Exact?
        backend:
          service:
            name: todo-api   # What service name?
            port:
              number: 3000
